public without sharing class communityWrapper {
        @AuraEnabled
        public string fName {get;set;}
        @AuraEnabled
        public string lName {get;set;}
        @AuraEnabled
        public string email {get;set;}
        @AuraEnabled
        public string uName {get;set;}
        @AuraEnabled
        public string company {get;set;}
        @AuraEnabled
        public string phone {get;set;}
        @AuraEnabled
        public string alias {get;set;}
        @AuraEnabled
        public string nickname {get;set;}
        @AuraEnabled
        public string profileId {get;set;}
        @AuraEnabled
        public string contactId {get;set;}
}